# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import promo_pb2 as promo__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in promo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PromoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckItemPromo = channel.unary_unary(
                '/promo.PromoService/CheckItemPromo',
                request_serializer=promo__pb2.CheckItemPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.CheckItemPromoResponse.FromString,
                _registered_method=True)
        self.CheckItemsPromos = channel.unary_unary(
                '/promo.PromoService/CheckItemsPromos',
                request_serializer=promo__pb2.CheckItemsPromosRequest.SerializeToString,
                response_deserializer=promo__pb2.CheckItemsPromosResponse.FromString,
                _registered_method=True)
        self.GetPromoByHash = channel.unary_unary(
                '/promo.PromoService/GetPromoByHash',
                request_serializer=promo__pb2.PromoByHashRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoByHashResponse.FromString,
                _registered_method=True)
        self.ListPromos = channel.unary_unary(
                '/promo.PromoService/ListPromos',
                request_serializer=promo__pb2.ListPromosRequest.SerializeToString,
                response_deserializer=promo__pb2.ListPromosResponse.FromString,
                _registered_method=True)
        self.DeletePromo = channel.unary_unary(
                '/promo.PromoService/DeletePromo',
                request_serializer=promo__pb2.DeletePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.DeletePromoResponse.FromString,
                _registered_method=True)
        self.CreateDiscountPromo = channel.unary_unary(
                '/promo.PromoService/CreateDiscountPromo',
                request_serializer=promo__pb2.CreateDiscountPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.UpdateDiscountPromo = channel.unary_unary(
                '/promo.PromoService/UpdateDiscountPromo',
                request_serializer=promo__pb2.UpdateDiscountPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.CreateBundlePromo = channel.unary_unary(
                '/promo.PromoService/CreateBundlePromo',
                request_serializer=promo__pb2.CreateBundlePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.UpdateBundlePromo = channel.unary_unary(
                '/promo.PromoService/UpdateBundlePromo',
                request_serializer=promo__pb2.UpdateBundlePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.CreateThresholdPromo = channel.unary_unary(
                '/promo.PromoService/CreateThresholdPromo',
                request_serializer=promo__pb2.CreateThresholdPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.UpdateThresholdPromo = channel.unary_unary(
                '/promo.PromoService/UpdateThresholdPromo',
                request_serializer=promo__pb2.UpdateThresholdPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.CreatePointPurchasePromo = channel.unary_unary(
                '/promo.PromoService/CreatePointPurchasePromo',
                request_serializer=promo__pb2.CreatePointPurchasePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.UpdatePointPurchasePromo = channel.unary_unary(
                '/promo.PromoService/UpdatePointPurchasePromo',
                request_serializer=promo__pb2.UpdatePointPurchasePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)


class PromoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckItemPromo(self, request, context):
        """Check promotion for a single item, including discount, point purchase, and optional coupon code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckItemsPromos(self, request, context):
        """Check promotion for a list of items to determine bundle or threshold-based promos with optional coupon code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromoByHash(self, request, context):
        """Other existing services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPromos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDiscountPromo(self, request, context):
        """Create/Update Promo types
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDiscountPromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBundlePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBundlePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateThresholdPromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateThresholdPromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePointPurchasePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePointPurchasePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckItemPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckItemPromo,
                    request_deserializer=promo__pb2.CheckItemPromoRequest.FromString,
                    response_serializer=promo__pb2.CheckItemPromoResponse.SerializeToString,
            ),
            'CheckItemsPromos': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckItemsPromos,
                    request_deserializer=promo__pb2.CheckItemsPromosRequest.FromString,
                    response_serializer=promo__pb2.CheckItemsPromosResponse.SerializeToString,
            ),
            'GetPromoByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromoByHash,
                    request_deserializer=promo__pb2.PromoByHashRequest.FromString,
                    response_serializer=promo__pb2.PromoByHashResponse.SerializeToString,
            ),
            'ListPromos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPromos,
                    request_deserializer=promo__pb2.ListPromosRequest.FromString,
                    response_serializer=promo__pb2.ListPromosResponse.SerializeToString,
            ),
            'DeletePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromo,
                    request_deserializer=promo__pb2.DeletePromoRequest.FromString,
                    response_serializer=promo__pb2.DeletePromoResponse.SerializeToString,
            ),
            'CreateDiscountPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDiscountPromo,
                    request_deserializer=promo__pb2.CreateDiscountPromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'UpdateDiscountPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDiscountPromo,
                    request_deserializer=promo__pb2.UpdateDiscountPromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'CreateBundlePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBundlePromo,
                    request_deserializer=promo__pb2.CreateBundlePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'UpdateBundlePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBundlePromo,
                    request_deserializer=promo__pb2.UpdateBundlePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'CreateThresholdPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThresholdPromo,
                    request_deserializer=promo__pb2.CreateThresholdPromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'UpdateThresholdPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateThresholdPromo,
                    request_deserializer=promo__pb2.UpdateThresholdPromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'CreatePointPurchasePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePointPurchasePromo,
                    request_deserializer=promo__pb2.CreatePointPurchasePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'UpdatePointPurchasePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePointPurchasePromo,
                    request_deserializer=promo__pb2.UpdatePointPurchasePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'promo.PromoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('promo.PromoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckItemPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CheckItemPromo',
            promo__pb2.CheckItemPromoRequest.SerializeToString,
            promo__pb2.CheckItemPromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckItemsPromos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CheckItemsPromos',
            promo__pb2.CheckItemsPromosRequest.SerializeToString,
            promo__pb2.CheckItemsPromosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromoByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/GetPromoByHash',
            promo__pb2.PromoByHashRequest.SerializeToString,
            promo__pb2.PromoByHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPromos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/ListPromos',
            promo__pb2.ListPromosRequest.SerializeToString,
            promo__pb2.ListPromosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/DeletePromo',
            promo__pb2.DeletePromoRequest.SerializeToString,
            promo__pb2.DeletePromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDiscountPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CreateDiscountPromo',
            promo__pb2.CreateDiscountPromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDiscountPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/UpdateDiscountPromo',
            promo__pb2.UpdateDiscountPromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBundlePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CreateBundlePromo',
            promo__pb2.CreateBundlePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBundlePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/UpdateBundlePromo',
            promo__pb2.UpdateBundlePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateThresholdPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CreateThresholdPromo',
            promo__pb2.CreateThresholdPromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateThresholdPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/UpdateThresholdPromo',
            promo__pb2.UpdateThresholdPromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePointPurchasePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CreatePointPurchasePromo',
            promo__pb2.CreatePointPurchasePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePointPurchasePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/UpdatePointPurchasePromo',
            promo__pb2.UpdatePointPurchasePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
