# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import catalogue_pb2 as catalogue__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CatalogueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/catalogue.CatalogueService/GetProduct',
                request_serializer=catalogue__pb2.GetProductRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/catalogue.CatalogueService/CreateProduct',
                request_serializer=catalogue__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/catalogue.CatalogueService/UpdateProduct',
                request_serializer=catalogue__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/catalogue.CatalogueService/DeleteProduct',
                request_serializer=catalogue__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=catalogue__pb2.Empty.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/catalogue.CatalogueService/ListProducts',
                request_serializer=catalogue__pb2.Empty.SerializeToString,
                response_deserializer=catalogue__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.GetCategory = channel.unary_unary(
                '/catalogue.CatalogueService/GetCategory',
                request_serializer=catalogue__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=catalogue__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.CreateCategory = channel.unary_unary(
                '/catalogue.CatalogueService/CreateCategory',
                request_serializer=catalogue__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=catalogue__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/catalogue.CatalogueService/UpdateCategory',
                request_serializer=catalogue__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=catalogue__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/catalogue.CatalogueService/DeleteCategory',
                request_serializer=catalogue__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=catalogue__pb2.Empty.FromString,
                _registered_method=True)
        self.ListCategories = channel.unary_unary(
                '/catalogue.CatalogueService/ListCategories',
                request_serializer=catalogue__pb2.Empty.SerializeToString,
                response_deserializer=catalogue__pb2.ListCategoriesResponse.FromString,
                _registered_method=True)


class CatalogueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Category CRUD operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=catalogue__pb2.GetProductRequest.FromString,
                    response_serializer=catalogue__pb2.ProductResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=catalogue__pb2.CreateProductRequest.FromString,
                    response_serializer=catalogue__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=catalogue__pb2.UpdateProductRequest.FromString,
                    response_serializer=catalogue__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=catalogue__pb2.DeleteProductRequest.FromString,
                    response_serializer=catalogue__pb2.Empty.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=catalogue__pb2.Empty.FromString,
                    response_serializer=catalogue__pb2.ListProductsResponse.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=catalogue__pb2.GetCategoryRequest.FromString,
                    response_serializer=catalogue__pb2.CategoryResponse.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=catalogue__pb2.CreateCategoryRequest.FromString,
                    response_serializer=catalogue__pb2.CategoryResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=catalogue__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=catalogue__pb2.CategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=catalogue__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=catalogue__pb2.Empty.SerializeToString,
            ),
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=catalogue__pb2.Empty.FromString,
                    response_serializer=catalogue__pb2.ListCategoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogue.CatalogueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogue.CatalogueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/GetProduct',
            catalogue__pb2.GetProductRequest.SerializeToString,
            catalogue__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/CreateProduct',
            catalogue__pb2.CreateProductRequest.SerializeToString,
            catalogue__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/UpdateProduct',
            catalogue__pb2.UpdateProductRequest.SerializeToString,
            catalogue__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/DeleteProduct',
            catalogue__pb2.DeleteProductRequest.SerializeToString,
            catalogue__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/ListProducts',
            catalogue__pb2.Empty.SerializeToString,
            catalogue__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/GetCategory',
            catalogue__pb2.GetCategoryRequest.SerializeToString,
            catalogue__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/CreateCategory',
            catalogue__pb2.CreateCategoryRequest.SerializeToString,
            catalogue__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/UpdateCategory',
            catalogue__pb2.UpdateCategoryRequest.SerializeToString,
            catalogue__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/DeleteCategory',
            catalogue__pb2.DeleteCategoryRequest.SerializeToString,
            catalogue__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.CatalogueService/ListCategories',
            catalogue__pb2.Empty.SerializeToString,
            catalogue__pb2.ListCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
