# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import checkout_pb2 as checkout__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in checkout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CheckoutServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCheckout = channel.unary_unary(
                '/checkout.CheckoutService/CreateCheckout',
                request_serializer=checkout__pb2.CreateCheckoutRequest.SerializeToString,
                response_deserializer=checkout__pb2.CheckoutResponse.FromString,
                _registered_method=True)
        self.ListCheckouts = channel.unary_unary(
                '/checkout.CheckoutService/ListCheckouts',
                request_serializer=checkout__pb2.ListCheckoutsRequest.SerializeToString,
                response_deserializer=checkout__pb2.ListCheckoutsResponse.FromString,
                _registered_method=True)
        self.GetCheckoutDetail = channel.unary_unary(
                '/checkout.CheckoutService/GetCheckoutDetail',
                request_serializer=checkout__pb2.GetCheckoutDetailRequest.SerializeToString,
                response_deserializer=checkout__pb2.CheckoutDetailResponse.FromString,
                _registered_method=True)
        self.UpdateCheckout = channel.unary_unary(
                '/checkout.CheckoutService/UpdateCheckout',
                request_serializer=checkout__pb2.UpdateCheckoutRequest.SerializeToString,
                response_deserializer=checkout__pb2.CheckoutResponse.FromString,
                _registered_method=True)
        self.DeleteCheckout = channel.unary_unary(
                '/checkout.CheckoutService/DeleteCheckout',
                request_serializer=checkout__pb2.DeleteCheckoutRequest.SerializeToString,
                response_deserializer=checkout__pb2.Empty.FromString,
                _registered_method=True)


class CheckoutServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckouts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckoutDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckout,
                    request_deserializer=checkout__pb2.CreateCheckoutRequest.FromString,
                    response_serializer=checkout__pb2.CheckoutResponse.SerializeToString,
            ),
            'ListCheckouts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckouts,
                    request_deserializer=checkout__pb2.ListCheckoutsRequest.FromString,
                    response_serializer=checkout__pb2.ListCheckoutsResponse.SerializeToString,
            ),
            'GetCheckoutDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckoutDetail,
                    request_deserializer=checkout__pb2.GetCheckoutDetailRequest.FromString,
                    response_serializer=checkout__pb2.CheckoutDetailResponse.SerializeToString,
            ),
            'UpdateCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCheckout,
                    request_deserializer=checkout__pb2.UpdateCheckoutRequest.FromString,
                    response_serializer=checkout__pb2.CheckoutResponse.SerializeToString,
            ),
            'DeleteCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCheckout,
                    request_deserializer=checkout__pb2.DeleteCheckoutRequest.FromString,
                    response_serializer=checkout__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.CheckoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checkout.CheckoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckoutService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.CheckoutService/CreateCheckout',
            checkout__pb2.CreateCheckoutRequest.SerializeToString,
            checkout__pb2.CheckoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckouts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.CheckoutService/ListCheckouts',
            checkout__pb2.ListCheckoutsRequest.SerializeToString,
            checkout__pb2.ListCheckoutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckoutDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.CheckoutService/GetCheckoutDetail',
            checkout__pb2.GetCheckoutDetailRequest.SerializeToString,
            checkout__pb2.CheckoutDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.CheckoutService/UpdateCheckout',
            checkout__pb2.UpdateCheckoutRequest.SerializeToString,
            checkout__pb2.CheckoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.CheckoutService/DeleteCheckout',
            checkout__pb2.DeleteCheckoutRequest.SerializeToString,
            checkout__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
